name = "Quasar"
author = "Timoti11"
version = "0.9.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce66519e2a30de9f23ea1a1c665dd63b9c899e79595a13b51431acd6b9d76302"

[versions]
minecraft = "1.19.4"
quilt = "0.18.10"
