name = "Quasar"
author = "Timoti11"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96a4e2f624fda1baedaf010145931e6bfd65047bdafa12f503af3f1a8c6689b5"

[versions]
minecraft = "1.20.1"
quilt = "0.19.0"

[options]
acceptable-game-versions = ["1.20"]
