name = "Quasar"
author = "Timoti11"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba20346a98c0fcc20b08d757a81b007531eaaa8100b1bb38728b9fdf785f28c1"

[versions]
minecraft = "1.20"
quilt = "0.19.0-beta.18"
