name = "Quasar"
author = "Timoti11"
version = "2.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd494b356ca78d4156b3cf07939c7292612d774ca876d26c473027f03deee40b"

[versions]
minecraft = "1.20"
quilt = "0.19.1"
