name = "Quasar"
author = "Timoti11"
version = "1.4.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5f80216084fcf006663557d3c3c77704f6e57b37e37dda5e0ff5633ab3cbd58"

[versions]
minecraft = "1.19.4"
quilt = "0.18.10"
