name = "Quasar"
author = "Timoti11"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e7869b7a22060be66db97407d2217e6a287f346365c93627fdb940068b95b7a"

[versions]
minecraft = "1.20.1"
quilt = "0.19.0"

[options]
acceptable-game-versions = ["1.20"]
