name = "Quasar"
author = "Timoti11"
version = "0.9.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6c8db0d92fbb7fbee931b5c0c4e8771c7593a71e3002621a07e21e05a3b570b"

[versions]
minecraft = "1.19.3"
quilt = "0.19.0-beta.12"
