name = "Quasar"
author = "Timoti11"
version = "3.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a10a691a30ec3d9b160ac2efc9dfce3d3979c74afc8df7528dd0bdf8e776ae70"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
