name = "Quasar"
author = "Timoti11"
version = "3.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41cbcf22a5844a6de68de0ead2fd1dcb4f806455ab782a6fb2f793f07ee77ae9"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
