name = "Quasar"
author = "Timoti11"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ccdf033ac613b5af13fd37c013210623da163470c92a75fb64e28567635215d2"

[versions]
fabric = "0.14.21"
minecraft = "1.20"
