name = "Quasar"
author = "Timoti11"
version = "2.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a1470b1179cb2979aa3ff115675af901462161ce77813de981ae1f640504c80"

[versions]
minecraft = "1.20"
quilt = "0.19.0-beta.18"
