name = "Quasar"
author = "Timoti11"
version = "2.0.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80a0ab9f7186e9172f1295ab5283631ae8c0ff15e982e9ff6e70281c7c29f764"

[versions]
minecraft = "1.20"
quilt = "0.19.1"
