name = "Quasar"
author = "Timoti11"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6d1265448a08d3e32e00f9e7d349647b9b9b7fcdbb9d9430fdabe767a608c00"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.11"
