name = "Quasar"
author = "Timoti11"
version = "0.9.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a55cd892b654172ba62f39717fd269a5dc1adab4d8e2a57b94e5a46f1c2a9fa"

[versions]
minecraft = "1.19.3"
quilt = "0.19.0-beta.12"