name = "Quasar"
author = "Timoti11"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82a332c1580ab7fb27df04437035bab99e786d7d185a696e6b7caf2692441b5b"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.11"
