name = "Quasar"
author = "Timoti11"
version = "2.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c5f3a6006c944ea4cfe33058222bebe8e14ff3534a6313f8fe056e66f2f4c35"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.11"
