name = "Quasar"
author = "Timoti11"
version = "2.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db1fd409fe971d1259cbb03f6d8386738de573d1a244908ceb483b2e23f1b80b"

[versions]
minecraft = "1.20"
quilt = "0.19.0-beta.18"
