name = "Quasar"
author = "Timoti11"
version = "0.9.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6890c975a5f450072cdbfa7384a75ca5b62dc229f2f3ec8b86658cac1bca4289"

[versions]
minecraft = "1.19.3"
quilt = "0.19.0-beta.12"