version = 3

[clientSideConfig]

	[clientSideConfig.modifyMaxVDConfig]
		enabled = false

[noTickViewDistance]
	compatibilityMode = false
	maxConcurrentChunkLoads = 1
	
[ioSystem]
	gcFreeChunkSerializer = true

