debug = false
disable_crowdin = false
check_for_updates = false

key_bindings = []

[servers.5b97d502-332a-4c4f-a21b-ed79b5b70f2d.distances]
4aec07ba-d109-3345-9a0a-92022a116cd0 = 32

[addons.pv-addon-soundphysics]
"gui.plasmovoice.soundphysics.mic_reverb_volume" = 1.0
"gui.plasmovoice.soundphysics.enabled" = true
"gui.plasmovoice.soundphysics.mic_reverb" = true

[voice]
disabled = false
microphone_disabled = false
activation_threshold = -30.0
input_device = ""
output_device = ""
use_javax_input = false
microphone_volume = 1.0
noise_suppression = false
volume = 1.0
compressor_limiter = true
sound_occlusion = false
directional_sources = false
hrtf = true
stereo_capture = true

[voice.volumes.source_8b66acba-3139-41b4-b73b-79db604c99d8]
volume = 1.0
[voice.volumes.proximity]
volume = 1.0
[voice.volumes.discs]
volume = 0.5

[advanced]
visualize_voice_distance = true
visualize_voice_distance_on_join = false
compressor_threshold = -10
limiter_threshold = -6
directional_sources_angle = 360
stereo_sources_to_mono = false
panning = true
camera_sound_listener = true
exponential_volume_slider = true
exponential_distance_gain = true

[overlay]
show_activation_icon = true
activation_icon_position = "BOTTOM_CENTER"
show_source_icons = 0
show_static_source_icons = true
overlay_enabled = true
overlay_position = "BOTTOM_LEFT"
overlay_style = "SKIN"

[overlay.source_states]
proximity = "ON"
discs = "ON"
